version: '3.5'

services:
  # rabbitmq:
  #   container_name: base_traning_rabbitmq
  #   image: rabbitmq:3-management
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
  #     - 25676:25676
  #   environment:
  #     RABBITMQ_DEFAULT_USER: ${RMQ_USER}
  #     RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}

  db:
    container_name: base_traning_postgresdb
    image: postgres:14
    volumes:
      - base_traning_postgresdb-data:/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - app-connect

volumes:
  base_traning_postgresdb-data:


networks:
  app-connect:
    driver: bridge